import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

const Slug = () => {
  const [data, setData] = useState();

  const router = useRouter();
  useEffect(() => {
    if (!router.isReady) return;
    const { slug } = router.query;
    console.log(router.query);
    fetch(`http://localhost:3000/api/getallblogs?slug=${slug}`)
      .then((a) => {
        return a.json();
      })
      .then((parsed) => {
        setData(parsed);
        console.log("Final Result", parsed);
      });
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>{data?.slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container my-5">
        <div className="container text-center text-white">
          <h3>This Post is {data?.title}</h3>
          <p className="my-3">{data?.content}</p>
        </div>
        <div className="text-center my-5">
          <Link href={`${data?.link}`} target="_blank" className="readMoreBtn "> 
            Read More...
          </Link>
        </div>
      </div>
    </>
  );
};

export default Slug;
