import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.scss";
import "../styles/navbar.scss";
import "../styles/main.scss";
import Navbar from "./navbar";
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
    <>
        <Head>
          <title>Practise App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}
