import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Practise App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Home Page content*/}
      <div className="glass">
        <img src="/images/bg_img.jpg" style={{backgroundSize:"cover", height:"80vh", width:"100%", padding:"10px 100px"}} className="greyWrapper" alt="" />
      </div>
      <div className="container text-center my-5">
        <h1 className="text-white">Wellcome to Home Page</h1>
        <p className="text-white">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem nihil
          incidunt consequuntur perferendis, adipisci eum repellendus blanditiis
          cumque? Numquam ab, suscipit molestias amet dolores facilis aperiam.
          Quo quia ipsam dolorum ex nobis, non vitae? Vero dolorem tempora
          itaque a quo, odit totam aliquid consequuntur neque ex aut quidem
          aspernatur et in, hic iusto incidunt fugit repellat repellendus, eius
          doloremque consectetur.
        </p>
        <button className="btn btn-lg bg-white">
          <Link href="/contact" className="text-dark" style={{textDecoration:"none"}}>Contact</Link>
        </button>
      </div>
    </>
  );
}
